name: Testes do Projeto

on:
  push:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencias
        run: npm install

      - name: Fix permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Run testes
        run: npx test
